-- QuickWash on Supabase: Postgres, Auth and row level security (SRS section 10).
-- Run once in Supabase -> SQL Editor. Safe to re-run: it drops first.
--
-- Sign-in is by mobile number. Supabase Auth is email-based, so a synthetic
-- address (0771111111@quickwash.local) carries the phone as the credential;
-- nobody ever sees or types it. public.users.auth_id is the link.

drop table if exists notifications, order_status_history,
                     laundry_orders, addresses, users, laundry_shops,
                     order_counters, settings cascade;

-- 10.5 Laundry shops ---------------------------------------------------------
-- First: users.shop_id references it, and Postgres has no forward FKs.
create table laundry_shops (
  id          bigint generated by default as identity primary key,
  name        text not null,
  phone       text,
  address     text,
  latitude    double precision,
  longitude   double precision,
  is_active   boolean     not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- 10.1 Users -----------------------------------------------------------------
create table users (
  id         bigint generated by default as identity primary key,
  auth_id    uuid unique references auth.users (id) on delete cascade,
  name       text not null,
  phone      text not null unique,
  email      text,
  role       text not null check (role in ('CUSTOMER','PICKUP_AGENT','SHOP_STAFF','ADMIN')),
  shop_id    bigint references laundry_shops (id) on delete set null,
  is_active  boolean     not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_users_role on users (role);
create index idx_users_auth on users (auth_id);

-- 10.2 Addresses -------------------------------------------------------------
create table addresses (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references users (id) on delete cascade,
  label      text not null,
  address    text not null,
  area       text,
  landmark   text,
  latitude   double precision,
  longitude  double precision,
  phone      text,
  is_deleted boolean     not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_addresses_user on addresses (user_id);

-- 10.3 Laundry orders --------------------------------------------------------
create table laundry_orders (
  id                bigint generated by default as identity primary key,
  order_number      text not null unique,
  customer_id       bigint not null references users (id) on delete restrict,
  pickup_agent_id   bigint references users (id) on delete set null,
  delivery_agent_id bigint references users (id) on delete set null,
  laundry_shop_id   bigint references laundry_shops (id) on delete set null,
  status            text not null default 'PENDING',
  pickup_address_id bigint not null references addresses (id) on delete restrict,
  pickup_date       date not null,
  pickup_time_slot  text not null,
  bag_count         integer not null,
  item_count        integer,
  actual_bag_count  integer,
  price             numeric(10,2),
  notes             text,
  picked_up_at      timestamptz,
  received_at       timestamptz,
  ready_at          timestamptz,
  delivered_at      timestamptz,
  cancelled_at      timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index idx_orders_customer on laundry_orders (customer_id);
create index idx_orders_status   on laundry_orders (status);
create index idx_orders_pickup   on laundry_orders (pickup_agent_id);
create index idx_orders_delivery on laundry_orders (delivery_agent_id);
create index idx_orders_date     on laundry_orders (pickup_date);

-- 10.4 Order status history --------------------------------------------------
create table order_status_history (
  id         bigint generated by default as identity primary key,
  order_id   bigint not null references laundry_orders (id) on delete cascade,
  status     text not null,
  changed_by bigint references users (id) on delete set null,
  notes      text,
  created_at timestamptz not null default now()
);
create index idx_history_order on order_status_history (order_id);

-- Notifications (FR-021) -----------------------------------------------------
create table notifications (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references users (id) on delete cascade,
  order_id   bigint references laundry_orders (id) on delete cascade,
  event      text not null,
  title      text not null,
  body       text not null,
  is_read    boolean     not null default false,
  created_at timestamptz not null default now()
);
create index idx_notifications_user on notifications (user_id, is_read);

-- Order-number counter (BR-002) ----------------------------------------------
create table order_counters (
  year integer primary key,
  last integer not null default 0
);

-- System settings ------------------------------------------------------------
create table settings (
  key   text primary key,
  value text not null
);


-- ============================================================================
-- Signup
-- ============================================================================
-- Every auth.users row gets a public.users row, and it is always a CUSTOMER.
--
-- Signup metadata is written by whoever calls signUp(), so it can never decide
-- a role: a crafted request would simply ask to be an administrator. Agents,
-- shop staff and admins are made by creating the account and then promoting
-- the row with the service role, which only the server holds
-- (see createUser() in src/lib/repos.ts).

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (auth_id, name, phone, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    nullif(new.raw_user_meta_data ->> 'contact_email', ''),
    'CUSTOMER'
  )
  on conflict (phone) do update set auth_id = excluded.auth_id;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- ============================================================================
-- What the access token carries
-- ============================================================================
-- Working out who is asking used to cost two network calls per request: one
-- to the Auth API to check the token, one to `users` for the role. The first
-- is gone in the app - getClaims() verifies the ES256 signature locally. This
-- removes the second by putting what the app needs in the token. Nothing
-- rests on the token being current: RLS reads `users` through my_role().

/**
 * Keeps the access token in step with the row. Supabase copies an account's
 * app_metadata into every token it issues, so this writes the row id, role,
 * shop and name there whenever they change - and src/lib/auth.ts reads the
 * session from the token without a query. Security definer: only the owner
 * may write to auth.users, which is also why the app never can.
 *
 * Existing accounts are backfilled once with scripts/sync-claims.ts. An open
 * session sees a change at its next token refresh (within the hour) or
 * sign-in; updateUser() ends the session outright when the shop or active
 * flag changes so nothing waits on that.
 */
create or replace function public.sync_user_claims()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  if new.auth_id is null then return new; end if;

  update auth.users
     set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb) || jsonb_build_object(
           'user_id',   new.id,
           'name',      new.name,
           'phone',     new.phone,
           'email',     new.email,
           'user_role', new.role,      -- not 'role': that is Postgres's own claim
           'shop_id',   new.shop_id,
           'is_active', new.is_active
         )
   where id = new.auth_id;

  return new;
end;
$$;

drop trigger if exists sync_user_claims on public.users;
create trigger sync_user_claims
  after insert or update of auth_id, name, phone, email, role, shop_id, is_active
  on public.users
  for each row execute function public.sync_user_claims();


-- ============================================================================
-- Predicate helpers
-- ============================================================================
-- All security definer, so they read past RLS. That is deliberate: a policy
-- that queried users directly would re-enter its own policy and recurse.

/** The caller's row id in public.users, or null when signed out. */
create or replace function public.me()
returns bigint
language sql stable security definer set search_path = public
as $$ select id from public.users where auth_id = auth.uid(); $$;

create or replace function public.my_role()
returns text
language sql stable security definer set search_path = public
as $$ select role from public.users where auth_id = auth.uid() and is_active; $$;

create or replace function public.my_shop()
returns bigint
language sql stable security definer set search_path = public
as $$ select shop_id from public.users where auth_id = auth.uid(); $$;

create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public
as $$ select public.my_role() = 'ADMIN'; $$;

/**
 * BR-008 / SRS section 12, as one predicate. The same rule as canViewOrder()
 * in src/lib/orders.ts - that one shapes the UI, this one is the lock.
 */
create or replace function public.can_view_order(order_id bigint)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1
      from public.laundry_orders o
     where o.id = order_id
       and case public.my_role()
             when 'ADMIN'        then true
             when 'CUSTOMER'     then o.customer_id = public.me()
             when 'PICKUP_AGENT' then o.pickup_agent_id = public.me()
                                    or o.delivery_agent_id = public.me()
             when 'SHOP_STAFF'   then public.my_shop() is null
                                    or o.laundry_shop_id = public.my_shop()
                                    or o.laundry_shop_id is null
             else false
           end
  );
$$;

/** BR-006: the transitions drawn in SRS section 9, and nothing else. */
create or replace function public.allowed_transition(from_status text, to_status text)
returns boolean
language sql immutable
as $$
  select case from_status
    when 'PENDING'          then to_status in ('PICKUP_ASSIGNED','CANCELLED')
    when 'PICKUP_ASSIGNED'  then to_status in ('PICKED_UP','PENDING','CANCELLED')
    when 'PICKED_UP'        then to_status = 'AT_LAUNDRY'
    when 'AT_LAUNDRY'       then to_status = 'WASHING'
    when 'WASHING'          then to_status = 'DRYING'
    when 'DRYING'           then to_status = 'IRONING'
    when 'IRONING'          then to_status = 'READY'
    when 'READY'            then to_status = 'OUT_FOR_DELIVERY'
    when 'OUT_FOR_DELIVERY' then to_status = 'DELIVERED'
    else false
  end;
$$;

/** BR-005: which role may move an order into a given status. */
create or replace function public.role_may_set(want_role text, to_status text)
returns boolean
language sql immutable
as $$
  select case to_status
    when 'PENDING'          then want_role = 'ADMIN'
    when 'PICKUP_ASSIGNED'  then want_role = 'ADMIN'
    when 'PICKED_UP'        then want_role in ('PICKUP_AGENT','ADMIN')
    when 'AT_LAUNDRY'       then want_role in ('SHOP_STAFF','ADMIN')
    when 'WASHING'          then want_role in ('SHOP_STAFF','ADMIN')
    when 'DRYING'           then want_role in ('SHOP_STAFF','ADMIN')
    when 'IRONING'          then want_role in ('SHOP_STAFF','ADMIN')
    when 'READY'            then want_role in ('SHOP_STAFF','ADMIN')
    when 'OUT_FOR_DELIVERY' then want_role = 'ADMIN'
    when 'DELIVERED'        then want_role in ('PICKUP_AGENT','ADMIN')
    when 'CANCELLED'        then want_role in ('CUSTOMER','ADMIN')
    else false
  end;
$$;


-- ============================================================================
-- Writes that must land together
-- ============================================================================
-- PostgREST has no client-side transaction, so the multi-row writes are
-- functions. Each is security definer and re-checks the caller: the anon key
-- ships to the browser, so "the app already checked" is not a check.

/**
 * One order in the shape OrderWithDetails describes, or null when the caller
 * may not see it. The write functions below return it, so nothing has to read
 * the order back over the network after changing it.
 *
 * Security definer to read past RLS on the joined tables, gated on
 * can_view_order() - which is what the RLS on those tables allows anyway: you
 * may read anyone named on an order you can already see.
 */
create or replace function public.order_details(p_order_id bigint)
returns json
language sql stable security definer set search_path = public
as $$
  select to_json(d) from (
    select o.*,
           coalesce(c.name, '')    as customer_name,
           coalesce(c.phone, '')   as customer_phone,
           pa.name                 as pickup_agent_name,
           pa.phone                as pickup_agent_phone,
           da.name                 as delivery_agent_name,
           s.name                  as shop_name,
           coalesce(a.label, '')   as address_label,
           coalesce(a.address, '') as address_line,
           a.area                  as address_area,
           a.landmark              as address_landmark,
           a.phone                 as address_phone
      from public.laundry_orders o
      left join public.users         c  on c.id  = o.customer_id
      left join public.users         pa on pa.id = o.pickup_agent_id
      left join public.users         da on da.id = o.delivery_agent_id
      left join public.laundry_shops s  on s.id  = o.laundry_shop_id
      left join public.addresses     a  on a.id  = o.pickup_address_id
     where o.id = p_order_id
       and public.can_view_order(p_order_id)
  ) d;
$$;

/** BR-002: the next order number, incremented atomically. */
create or replace function public.next_order_number()
returns text
language plpgsql security definer set search_path = public
as $$
declare
  y integer := extract(year from now())::integer;
  n integer;
begin
  insert into public.order_counters (year, last) values (y, 1)
  on conflict (year) do update set last = public.order_counters.last + 1
  returning last into n;
  return 'PU-' || y || '-' || lpad(n::text, 4, '0');
end;
$$;

/**
 * FR-005 / FR-006: a PENDING order plus its first history row (BR-007), and
 * the order number, in one transaction.
 */
create or replace function public.create_order(
  p_address_id       bigint,
  p_pickup_date      date,
  p_pickup_time_slot text,
  p_bag_count        integer,
  p_item_count       integer default null,
  p_notes            text default null,
  p_customer_id      bigint default null
)
returns json
language plpgsql security definer set search_path = public
as $$
declare
  actor    bigint := public.me();
  customer bigint := coalesce(p_customer_id, public.me());
  shop     bigint;
  new_id   bigint;
begin
  if actor is null then raise exception 'NOT_SIGNED_IN'; end if;
  -- Only an administrator may raise an order on someone else's behalf.
  if customer <> actor and not public.is_admin() then
    raise exception 'FORBIDDEN';
  end if;
  if p_bag_count < 1 then raise exception 'BAD_BAG_COUNT'; end if;

  -- BR-001: the pickup address must exist and belong to the customer.
  if not exists (
    select 1 from public.addresses
     where id = p_address_id and user_id = customer and not is_deleted
  ) then
    raise exception 'BAD_ADDRESS';
  end if;

  -- For the MVP a single active shop receives every order (FR-026).
  select id into shop from public.laundry_shops where is_active order by id limit 1;

  insert into public.laundry_orders
    (order_number, customer_id, laundry_shop_id, status, pickup_address_id,
     pickup_date, pickup_time_slot, bag_count, item_count, notes)
  values
    (public.next_order_number(), customer, shop, 'PENDING', p_address_id,
     p_pickup_date, p_pickup_time_slot, p_bag_count, p_item_count, p_notes)
  returning id into new_id;

  insert into public.order_status_history (order_id, status, changed_by, notes)
  values (new_id, 'PENDING', actor, 'Pickup requested');

  return public.order_details(new_id);
end;
$$;

/**
 * BR-004, BR-005, BR-006, BR-007, BR-009: the status change and its history
 * row, together. src/lib/orders.ts checks the same rules to shape the UI;
 * these are the ones that actually hold.
 */
create or replace function public.transition_order(
  p_order_id  bigint,
  p_to        text,
  p_notes     text default null,
  p_actual_bags integer default null
)
returns json
language plpgsql security definer set search_path = public
as $$
declare
  actor bigint := public.me();
  who   text   := public.my_role();
  o     record;
  stamp text;
begin
  if actor is null then raise exception 'NOT_SIGNED_IN'; end if;

  select * into o from public.laundry_orders where id = p_order_id for update;
  if not found then raise exception 'NOT_FOUND'; end if;

  if not public.can_view_order(p_order_id) then raise exception 'FORBIDDEN'; end if;
  if not public.role_may_set(who, p_to) then raise exception 'FORBIDDEN'; end if;

  -- BR-009: a completed order can only be touched by an administrator.
  if o.status = 'DELIVERED' and who <> 'ADMIN' then raise exception 'ALREADY_DONE'; end if;

  -- BR-004: an agent may only update orders assigned to them.
  if who = 'PICKUP_AGENT' then
    if p_to = 'DELIVERED' then
      if o.delivery_agent_id is distinct from actor then raise exception 'FORBIDDEN'; end if;
    elsif o.pickup_agent_id is distinct from actor then
      raise exception 'FORBIDDEN';
    end if;
  end if;

  if o.status = p_to then return public.order_details(p_order_id); end if;
  if not public.allowed_transition(o.status, p_to) then raise exception 'BAD_TRANSITION'; end if;

  -- FR-014 before FR-015: READY tells the customer what they owe, so the
  -- shop must have priced the order before it can say so.
  if p_to = 'READY' and o.price is null then raise exception 'PRICE_REQUIRED'; end if;

  stamp := case p_to
             when 'PICKED_UP' then 'picked_up_at'
             when 'AT_LAUNDRY' then 'received_at'
             when 'READY' then 'ready_at'
             when 'DELIVERED' then 'delivered_at'
             when 'CANCELLED' then 'cancelled_at'
           end;

  update public.laundry_orders
     set status           = p_to,
         actual_bag_count = coalesce(p_actual_bags, actual_bag_count),
         updated_at       = now(),
         picked_up_at = case when stamp = 'picked_up_at' then now() else picked_up_at end,
         received_at  = case when stamp = 'received_at'  then now() else received_at  end,
         ready_at     = case when stamp = 'ready_at'     then now() else ready_at     end,
         delivered_at = case when stamp = 'delivered_at' then now() else delivered_at end,
         cancelled_at = case when stamp = 'cancelled_at' then now() else cancelled_at end
   where id = p_order_id;

  insert into public.order_status_history (order_id, status, changed_by, notes)
  values (p_order_id, p_to, actor, coalesce(p_notes, p_to));

  return public.order_details(p_order_id);
end;
$$;

/** FR-014 / BR-010: the price and its history row together. */
create or replace function public.set_order_price(p_order_id bigint, p_price numeric)
returns json
language plpgsql security definer set search_path = public
as $$
declare
  actor bigint := public.me();
  who   text   := public.my_role();
  o     record;
begin
  if actor is null then raise exception 'NOT_SIGNED_IN'; end if;
  if who not in ('SHOP_STAFF','ADMIN') then raise exception 'FORBIDDEN'; end if;
  if p_price < 0 then raise exception 'BAD_PRICE'; end if;

  select * into o from public.laundry_orders where id = p_order_id for update;
  if not found then raise exception 'NOT_FOUND'; end if;
  if not public.can_view_order(p_order_id) then raise exception 'FORBIDDEN'; end if;
  if o.status = 'DELIVERED' and who <> 'ADMIN' then raise exception 'ALREADY_DONE'; end if;

  update public.laundry_orders set price = p_price, updated_at = now() where id = p_order_id;
  insert into public.order_status_history (order_id, status, changed_by, notes)
  values (p_order_id, o.status, actor,
          'Price set to LKR ' || trim(to_char(p_price, 'FM999,999,990.00')));

  return public.order_details(p_order_id);
end;
$$;

/** FR-007 / FR-016 (BR-003): only an administrator assigns agents. */
create or replace function public.assign_agent(
  p_order_id bigint,
  p_agent_id bigint,
  p_delivery boolean default false
)
returns json
language plpgsql security definer set search_path = public
as $$
declare
  current_status text;
begin
  if not public.is_admin() then raise exception 'FORBIDDEN'; end if;
  if not exists (
    select 1 from public.users
     where id = p_agent_id and role = 'PICKUP_AGENT' and is_active
  ) then
    raise exception 'AGENT_UNAVAILABLE';
  end if;

  -- The stage check lives here rather than in the caller so that reading the
  -- status and writing the agent cannot be two separate round trips, and
  -- cannot interleave with someone else moving the order on.
  select status into current_status
    from public.laundry_orders where id = p_order_id for update;
  if not found then raise exception 'NOT_FOUND'; end if;

  if p_delivery then
    if current_status not in ('READY','OUT_FOR_DELIVERY') then
      raise exception 'BAD_STAGE_DELIVERY';
    end if;
  else
    if current_status not in ('PENDING','PICKUP_ASSIGNED') then
      raise exception 'BAD_STAGE_PICKUP';
    end if;
  end if;

  if p_delivery then
    update public.laundry_orders
       set delivery_agent_id = p_agent_id, updated_at = now()
     where id = p_order_id;
  else
    update public.laundry_orders
       set pickup_agent_id = p_agent_id, updated_at = now()
     where id = p_order_id;
  end if;

  return public.order_details(p_order_id);
end;
$$;

/** FR-021: notifications are written on the caller's behalf by the services. */
create or replace function public.notify_users(
  p_user_ids bigint[],
  p_order_id bigint,
  p_event    text,
  p_title    text,
  p_body     text
)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  if public.me() is null then raise exception 'NOT_SIGNED_IN'; end if;
  insert into public.notifications (user_id, order_id, event, title, body)
  select unnest(p_user_ids), p_order_id, p_event, p_title, p_body;
end;
$$;

/**
 * FR-021, the recipient half. notify() used to ask `users` who the shop staff
 * are and then hand the list back - two round trips for one notification.
 *
 * The recipient matrix (SRS section 19) still lives in
 * src/lib/notification-events.ts, which is where the wording is; only "which
 * ids is that" happens here, where the rows already are.
 */
create or replace function public.notify_order(
  p_order_id   bigint,
  p_audiences  text[],
  p_event      text,
  p_title      text,
  p_body       text
)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  if public.me() is null then raise exception 'NOT_SIGNED_IN'; end if;
  if not exists (select 1 from public.laundry_orders where id = p_order_id) then
    raise exception 'NOT_FOUND';
  end if;

  insert into public.notifications (user_id, order_id, event, title, body)
  select r.id, p_order_id, p_event, p_title, p_body from (
    select o.customer_id as id from public.laundry_orders o
     where o.id = p_order_id and 'customer' = any (p_audiences)
    union
    select o.pickup_agent_id from public.laundry_orders o
     where o.id = p_order_id and 'pickup_agent' = any (p_audiences)
    union
    select o.delivery_agent_id from public.laundry_orders o
     where o.id = p_order_id and 'delivery_agent' = any (p_audiences)
    union
    -- Shop notifications go to every active staff member of the assigned shop;
    -- an order not yet routed to one goes to all of them.
    select u.id from public.users u, public.laundry_orders o
     where o.id = p_order_id and 'shop' = any (p_audiences)
       and u.role = 'SHOP_STAFF'
       and u.is_active
       and (o.laundry_shop_id is null or u.shop_id = o.laundry_shop_id)
  ) r
  where r.id is not null;
end;
$$;


/**
 * "You may edit your own profile" must not mean "you may edit your own role".
 *
 * RLS grants or denies a whole row, so a policy that lets you update yourself
 * lets you update every column of yourself - including role. This trigger is
 * what makes the column list real. auth.uid() is null for the service role,
 * which is how createUser() promotes a new staff account.
 */
create or replace function public.guard_user_columns()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then return new; end if;   -- service role
  if public.is_admin() then return new; end if;

  if new.id      is distinct from old.id
  or new.auth_id is distinct from old.auth_id
  or new.role    is distinct from old.role
  or new.shop_id is distinct from old.shop_id
  or new.is_active is distinct from old.is_active then
    raise exception 'FORBIDDEN: only an administrator may change a role, shop or account status';
  end if;

  return new;
end;
$$;

drop trigger if exists guard_user_columns on public.users;
create trigger guard_user_columns
  before update on public.users
  for each row execute function public.guard_user_columns();


-- ============================================================================
-- Views
-- ============================================================================
-- PostgREST has no GROUP BY and no correlated subquery, and the dashboards ask
-- for both. security_invoker means these run as the caller, so the row level
-- security on the underlying tables still applies through them.

/** FR-025: how much work each agent is currently carrying. */
create or replace view agent_workload
with (security_invoker = on) as
  select u.*,
         (select count(*) from public.laundry_orders o
           where o.pickup_agent_id = u.id and o.status = 'PICKUP_ASSIGNED')    as active_pickups,
         (select count(*) from public.laundry_orders o
           where o.delivery_agent_id = u.id and o.status = 'OUT_FOR_DELIVERY') as active_deliveries,
         (select count(*) from public.laundry_orders o
           where o.delivery_agent_id = u.id and o.status = 'DELIVERED')        as completed
    from public.users u
   where u.role = 'PICKUP_AGENT';

/** FR-024: customers with their order totals. */
create or replace view customer_summary
with (security_invoker = on) as
  select u.*,
         (select count(*) from public.laundry_orders o where o.customer_id = u.id) as order_count,
         (select sum(o.price) from public.laundry_orders o
           where o.customer_id = u.id and o.status = 'DELIVERED')                  as total_spend,
         (select max(o.created_at) from public.laundry_orders o
           where o.customer_id = u.id)                                             as last_order_at
    from public.users u
   where u.role = 'CUSTOMER';

/**
 * FR-023: the board, one row per status. statusCounts() used to select every
 * order's status column and count the rows in JavaScript - the whole table
 * over the wire, on a dashboard that asks for it twice.
 */
create or replace view order_status_counts
with (security_invoker = on) as
  select status, count(*)::integer as total
    from public.laundry_orders
   group by status;

/** The same, for the "today" panel: one row per status per pickup date. */
create or replace view order_status_counts_by_date
with (security_invoker = on) as
  select pickup_date, status, count(*)::integer as total
    from public.laundry_orders
   group by pickup_date, status;


-- ============================================================================
-- Row level security
-- ============================================================================
-- src/lib/ checks roles too. These policies mean the anon key, which ships to
-- the browser, still cannot reach anything it should not.

alter table users                enable row level security;
alter table addresses            enable row level security;
alter table laundry_shops        enable row level security;
alter table laundry_orders       enable row level security;
alter table order_status_history enable row level security;
alter table notifications        enable row level security;
alter table settings             enable row level security;
alter table order_counters       enable row level security;

-- Users ----------------------------------------------------------------------
-- You always see yourself. Staff see the people they work with: an admin sees
-- everyone, an agent and the shop see the customers on their own orders.
create policy "users read themselves and their counterparts" on users
  for select using (
    auth_id = auth.uid()
    or public.is_admin()
    -- Anyone named on an order you are allowed to see. Symmetric on purpose:
    -- the customer needs the agent's number as much as the agent needs theirs.
    -- Inlined rather than calling can_view_order() so this is one scan, not
    -- one definer call per row.
    or exists (
      select 1 from public.laundry_orders o
       where users.id in (o.customer_id, o.pickup_agent_id, o.delivery_agent_id)
         and case public.my_role()
               when 'CUSTOMER'     then o.customer_id = public.me()
               when 'PICKUP_AGENT' then o.pickup_agent_id = public.me()
                                      or o.delivery_agent_id = public.me()
               when 'SHOP_STAFF'   then public.my_shop() is null
                                      or o.laundry_shop_id = public.my_shop()
                                      or o.laundry_shop_id is null
               else false
             end
    )
  );

create policy "you edit your own profile" on users
  for update using (auth_id = auth.uid()) with check (auth_id = auth.uid());

create policy "admins manage accounts" on users
  for all using (public.is_admin()) with check (public.is_admin());

-- Addresses ------------------------------------------------------------------
create policy "your own address book" on addresses
  for select using (
    user_id = public.me()
    or public.is_admin()
    -- The agent at the door needs the address of the order they are collecting.
    or exists (
      select 1 from public.laundry_orders o
       where o.pickup_address_id = addresses.id and public.can_view_order(o.id)
    )
  );

create policy "you manage your own addresses" on addresses
  for all using (user_id = public.me() or public.is_admin())
  with check (user_id = public.me() or public.is_admin());

-- Laundry shops --------------------------------------------------------------
create policy "shops are readable by anyone signed in" on laundry_shops
  for select using (public.me() is not null);

create policy "admins manage shops" on laundry_shops
  for all using (public.is_admin()) with check (public.is_admin());

-- Orders ---------------------------------------------------------------------
-- BR-008. Writes go through the functions above, which is why there is no
-- insert or update policy here: only an admin may touch a row directly.
create policy "orders follow BR-008" on laundry_orders
  for select using (public.can_view_order(id));

create policy "admins edit orders directly" on laundry_orders
  for all using (public.is_admin()) with check (public.is_admin());

-- Status history -------------------------------------------------------------
create policy "history follows its order" on order_status_history
  for select using (public.can_view_order(order_id));

-- Notifications --------------------------------------------------------------
create policy "your own notifications" on notifications
  for select using (user_id = public.me());

create policy "you mark your own as read" on notifications
  for update using (user_id = public.me()) with check (user_id = public.me());

-- Settings -------------------------------------------------------------------
create policy "settings are readable by anyone signed in" on settings
  for select using (public.me() is not null);

create policy "admins edit settings" on settings
  for all using (public.is_admin()) with check (public.is_admin());

-- order_counters has no policy at all: it is reached only through
-- next_order_number(), which is security definer. RLS on with no policy means
-- no direct access, which is exactly right.
