-- Web Push subscriptions (FR-018, 2026-09-11).
--
-- Paste this into Supabase -> SQL Editor. It is incremental and safe to
-- re-run, and touches no data. The same block is at the end of schema.sql,
-- so a fresh project needs only that.
--
-- The customer's browser now hands the app a push subscription when they
-- turn notifications on, and the app posts to it when an order moves - which
-- reaches a phone with the site closed. This is the table those live in.

-- 10.x Push subscriptions (FR-018) ------------------------------------------
-- One row per device that asked to be told when its owner's orders move: the
-- endpoint at the browser's push service and the two keys that encrypt to
-- it. Written and read by src/lib/push.ts with the service role, because an
-- admin moving an order needs the customer's rows. The policy below is what
-- a customer may do directly: see and remove their own.
create table if not exists push_subscriptions (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references users (id) on delete cascade,
  endpoint   text not null unique,
  p256dh     text not null,
  auth       text not null,
  user_agent text,
  created_at timestamptz not null default now()
);
create index if not exists idx_push_user on push_subscriptions (user_id);

alter table push_subscriptions enable row level security;
drop policy if exists "your own push subscriptions" on push_subscriptions;
create policy "your own push subscriptions" on push_subscriptions
  for all using (user_id = public.me()) with check (user_id = public.me());
